name: Build and Update Helm Chart

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      commit_hash: ${{ steps.vars.outputs.commit_hash }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        email: ${{ secrets.DOCKER_EMAIL }}

    - name: Get commit hash
      id: vars
      run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest,${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ steps.vars.outputs.commit_hash }}

  update-helm:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout Helm Chart repository
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.GH_USERNAME }}/helm-chart-repo
        token: ${{ secrets.GH_TOKEN }}
        path: helm-chart-repo

    - name: Update values.yaml with new tag
      run: |
        sed -i 's/tag:.*/tag: '${{ needs.build-and-push.outputs.commit_hash }}'/' helm-chart-repo/probilet-backend/values.yaml

    - name: Commit and push changes
      run: |
        cd helm-chart-repo
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add probilet-backend/values.yaml
        git commit -m "Update Docker image tag to ${{ needs.build-and-push.outputs.commit_hash }}"
        git push
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
